project_id = "hmmimemzznsyilxqakty"

[auth.email.recovery]
enabled = true

[auth.email.recovery.webhook]
enabled = true
url = "https://hmmimemzznsyilxqakty.supabase.co/functions/v1/send-email"
events = ["recovery"]

[auth.email.signup]
enabled = true

[auth.email.signup.webhook]
enabled = true
url = "https://hmmimemzznsyilxqakty.supabase.co/functions/v1/send-email"
events = ["signup"]

[functions.send-email]
verify_jwt = false